theme: jekyll-theme-slate
title: Characterizing Regression in Deep Learning Model Evolution
description: Detailed Results and Implementation

github:
  is_project_page: false
show_downloads: false

markdown: kramdown